name: Publish docsite

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.any_changed }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.1.0
      - name: Check if docsite files are modified
        id: changes
        uses: tj-actions/changed-files@v32
        with:
          files: |
            docsite/**

  build-and-publish:
    runs-on: ubuntu-latest
    needs: [ dispatcher ]
    if: needs.dispatcher.outputs.changes == 'true'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.1.0
      - name: Build docsite
        run: |
          cd docsite
          npm install
          npm run build
      - name: Release docsite to Github Pages
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          BRANCH: gh-pages
          FOLDER: docsite/build
